**Note: In Data Science googling is a very important skill. If you find some difficulties to solve the problem, google it and try to find some clues to solve.**

In [1]:
import numpy as np

### `Q-1` Create a null vector of size 10 but the fifth value which is 1.

In [3]:
zeros = np.zeros(10)
zeros[4] = 1
zeros

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

### `Q-2` Ask user to input two numbers a, b. Write a program to generate a random array of shape (a, b) and print the array and avg of the array.

In [35]:
#Code here
a = int(input("Enter first Number: "))
b = int(input("Enter second Number: "))
random_array = np.round((np.random.random((a,b))*100),3)
array_avg = np.mean(random_array)
print(f"The Given Array is: \n{random_array}")
print(f"\nThe Average of Given Array is: {array_avg}")

Enter first Number:  4
Enter second Number:  4


The Given Array is: 
[[90.705 62.471 74.56  94.377]
 [55.585 33.317 30.914 45.609]
 [ 2.846 58.782 33.77  13.506]
 [26.347 35.654  5.585 12.327]]

The Average of Given Array is: 42.2721875


array([[82.36938634, 77.29596284, 75.25850714],
       [45.90245079, 24.90947059, 88.38199998],
       [29.15233472,  9.95413299, 12.13716827]])

### `Q-3`Write a function to create a 2d array with 1 on the border and 0 inside. Take 2-D array shape as (a,b) as parameter to function.

Eg.-
```
[[1,1,1,1],
[1,0,0,1],
[1,0,0,1],
[1,1,1,1]]
```

In [16]:
#Code here
def Two_Dim_array(a,b):
    border_ones = np.zeros((a,b))
    border_ones[0,:] = 1
    border_ones[:,0] = 1
    border_ones[-1,:] = 1
    border_ones[:,-1] = 1
    return border_ones

In [17]:
Two_Dim_array(6,6)

array([[1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [9]:
zeros = np.zeros((4,5))
zeros[1:-1,1:-1] = 1
zeros

array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

### `Q-4` Create a vector of size 10 with values ranging from 0 to 1, both excluded.

In [43]:
#Code here
vector = np.linspace(0,1,12)[1:-1]
print(f"output Vector: \n{vector}")

output Vector: 
[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


### `Q-5` Can you create a identity mattrix of shape (3,4). If yes write code for it.

you're looking for an identity matrix of shape (3, 4), it's not possible to create a traditional identity matrix because the number of rows and columns must be equal for an identity matrix.


### `Q-6:` Create a 5x5 matrix with row values ranging from 0 to 4.

In [76]:
#Code here
matrix = np.arange(0,25).reshape(5,5)
matrix[1:,:] = matrix[1:,:]%5
matrix

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

### `Q-7:`  Consider a random integer (in range 1 to 100) vector with shape `(10,2)` representing coordinates, and coordinates of a point as array is given. Create an array of distance of each point in the random vectros from the given point. Distance array should be interger type.

```
point = np.array([2,3])
```


In [78]:
#code here
# Given point
point = np.array([2, 3])
# Create a random integer vector with shape (10, 2) representing coordinates
random_vector = np.random.randint(1, 101, size=(10, 2))
# Calculate the distance between each point in the random vector and the given point
distances = np.linalg.norm(random_vector - point, axis=1).astype(int)
print("Random Vector:")
print(random_vector)
print("\nDistances from the given point:")
print(distances)

Random Vector:
[[93 79]
 [84 46]
 [60 38]
 [21 16]
 [70 71]
 [86 68]
 [ 5 60]
 [77 80]
 [ 4 16]
 [69 96]]

Distances from the given point:
[118  92  67  23  96 106  57 107  13 114]


### `Q-8:` Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [91]:
shape = (6, 7, 8)
flat_index = 100
# Use unravel_index to get the indices (x, y, z)
indices = np.unravel_index(flat_index, shape)
print("Indices (x, y, z):", indices)

Indices (x, y, z): (1, 5, 4)


### `Q-9:` Arrays
You are given a space separated list of numbers. Your task is to print a reversed NumPy array with the element type float.



**Input Format:**

A single line of input containing space separated numbers.

**Output Format:**

Print the reverse NumPy array with type float.

**Example 1:**

Input:

```bash
1 2 3 4 -8 -10
```

Output:

```bash
[-10.  -8.   4.   3.   2.   1.]
```

In [10]:
#Code here
arr = input("Enter a list with space seprated: ").strip().split(' ')
array = np.array(arr,dtype=float)
reverse = array[::-1]
print(reverse)

Enter a list with space seprated:  4 5 6 7 587 2 4 


[  4.   2. 587.   7.   6.   5.   4.]


### `Q-10:` Elements count

Count the number of elements of a numpy array.



**Example 1:**

Input:
```bash
np.array([])
```

Output:
```bash
elements_count :  0
```

**Example 2:**

Input:
```bash
np.array([1, 2])
```

Output:
```bash
elements_count :  2
```

In [111]:
#Code here
alist = input("Enter a list: ").split()
arr = np.array(alist)
elements_count = arr.size
print(elements_count)

Enter a list:  8 8 42 4 569 9 71


7


### `Q-11:` Softmax function

Create a Python function to calculate the Softmax of the given numpy 1D array. The function only accepts the numpy 1D array, otherwise raise error.

$$\Large \sigma(\vec z)_i = \frac{e^{z_i}}{\sum_{j=i}^{K}{e^{z_j}}}$$

https://en.wikipedia.org/wiki/Softmax_function



**Example 1:**

Input:
```bash
[86.03331084 37.7285648  48.64908087 87.16563062 38.40852563 37.20006318]
```

Output:
```bash
[2.43733249e-01, 2.56112115e-22, 1.41628284e-17, 7.56266751e-01,
       5.05514197e-22, 1.50974911e-22]
```

**Example 2:**

Input:
```bash
[33.17344305 45.61961654 82.05405781 80.9647098  68.82830233 91.52064278]
```

Output:
```bash
[4.57181035e-26, 1.16249923e-20, 7.73872596e-05, 2.60358426e-05,
       1.39571531e-10, 9.99896577e-01]
```

In [14]:
#Code here
def softmax(arr):
    sum = np.sum(np.exp(arr))
    exp = np.exp(arr)
    return exp/sum
softmax([33.17344305,45.61961654,82.05405781,80.9647098,68.82830233,91.52064278])    

array([4.57181033e-26, 1.16249922e-20, 7.73872594e-05, 2.60358426e-05,
       1.39571531e-10, 9.99896577e-01])

### `Q-12:` Vertical stack

Write a python function that accepts infinite number of numpy arrays and do the vertical stack to them. Then return that new array as result. The function only accepts the numpy array, otherwise raise error.



**Example 1:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]
```

Output:

```bash
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
```

**Example 2:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]

c= [[0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

Output:
```bash
[[0.         1.         2.         3.         4.        ]
 [5.         6.         7.         8.         9.        ]
 [1.         1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.        ]
 [0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

In [36]:
#Coder here
def vstack_func(*arg):
    for i in arg:
        if type(i) != np.ndarray:
            raise TypeError("Requires Numpy Array")
    vertical = np.vstack((arg))
    return vertical
a = np.arange(0,9).reshape(3,3)
b = np.arange(9,18).reshape(3,3)
c = np.random.random((3,3))*100
vstack_func(a,b,c)

array([[ 0.        ,  1.        ,  2.        ],
       [ 3.        ,  4.        ,  5.        ],
       [ 6.        ,  7.        ,  8.        ],
       [ 9.        , 10.        , 11.        ],
       [12.        , 13.        , 14.        ],
       [15.        , 16.        , 17.        ],
       [24.98076663, 30.20512185, 88.42324767],
       [65.44171042, 26.66913536, 79.01827104],
       [ 7.90884304, 66.41469327, 24.98481772]])

### `Q-13:` Dates

Create a python function named **date_array** that accepts two dates as string format and returns a numpy array of dates between those 2 dates. The function only accept 2 strings, otherwise raise error. The date format should be like this only: `2022-12-6`. The end date should be included and for simplicity, choose dates from a same year.



**Example 1:**

Input:
```bash
date_array(start = '2020-09-15', end = '2020-09-25')
```

Output:
```bash
['2020-09-15', '2020-09-16', '2020-09-17', '2020-09-18',
 '2020-09-19', '2020-09-20', '2020-09-21', '2020-09-22',
 '2020-09-23', '2020-09-24', '2020-09-25']
```

**Example 2:**

Input:
```bash
date_array(start = '2022-12-01', end = '2022-12-06')
```

Output:
```bash
['2022-12-01', '2022-12-02', '2022-12-03', '2022-12-04', '2022-12-05', '2022-12-06']
```

**Example 3:**

Input:
```bash
date_array(start = '2020-11-25', end = '2020-11-30')
```

Output:
```bash
['2020-11-25', '2020-11-26', '2020-11-27', '2020-11-28',
 '2020-11-29', '2020-11-30']
```

In [ ]:
#Code here

###`Q-14:` Subtract the mean of each row from a matrix.

In [45]:
#code here
x = np.random.random((4,5))*100
print(x)
print(x.mean(axis=1).shape)
x1= x.mean(axis=1,keepdims=True)
print(x1)
subtract = x1 - x
print(subtract)

[[52.02239666 27.90551563 69.50028562 88.52062758 46.57766558]
 [86.73484459 18.78883065 66.38104512 20.34131464 75.49466477]
 [33.7714439  63.14643467  8.94415258 24.48449391 58.79835504]
 [45.07032863 50.47485024 13.04177381 35.59524774 15.24488286]]
(4,)
[[56.90529821]
 [53.54813995]
 [37.82897602]
 [31.88541665]]
[[  4.88290156  28.99978258 -12.5949874  -31.61532937  10.32763264]
 [-33.18670464  34.7593093  -12.83290517  33.20682531 -21.94652481]
 [  4.05753212 -25.31745865  28.88482344  13.34448211 -20.96937902]
 [-13.18491197 -18.58943358  18.84364285  -3.70983109  16.6405338 ]]


###`Q-15:` Swap column-1 of array with column-2 in the array.

In [54]:
#Code here
arr = np.arange(1,10).reshape(3,3)
print(arr)
arr[:,[0,1]] = arr[:,[1,0]]
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2 1 3]
 [5 4 6]
 [8 7 9]]


###`Q-16:` Replace odd elements in arrays with -1.

In [56]:
#Code here
a = np.arange(9)
a[::2] = -1
a

array([-1,  1, -1,  3, -1,  5, -1,  7, -1])

In [58]:
a= np.arange(9).reshape(3,3)
a[a%2==1] = -1
a

array([[ 0, -1,  2],
       [-1,  4, -1],
       [ 6, -1,  8]])

###`Q-17:` Given two arrays of same shape make an array of max out of two arrays. (Numpy way)
```
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])

Result-> [6 3 1 7 8]
```

In [82]:
#Code here
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])
a[b>a] = b[a<b]
a

array([6, 3, 1, 7, 8])

In [105]:
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])
merge = np.vstack([a,b])
print(merge)
merge.max(axis=0)

[[6 3 1 5 8]
 [3 2 1 7 2]]


array([6, 3, 1, 7, 8])

###`Q-18` Answer below asked questions on given array:
1. Fetch Every alternate column of the array
2. Normalise the given array

https://en.wikipedia.org/wiki/Normalization_(statistics)

There are different form of normalisation for this question use below formula.

$$\large X_{normalized} = \frac{X - X_{min}}{X_{max} - X_{min}}$$

```python
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
```


In [83]:
# Given
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
arr1

array([[1996, 2455, 7227, 3789, 1126],
       [2554, 7814, 2818, 1953, 1109],
       [1567, 3645, 6410, 2386, 8247],
       [ 364, 3576, 6481, 9838, 1055],
       [9065, 6620, 6495, 5111, 4783],
       [1274, 3995, 3186, 1504, 2397],
       [1066, 1280, 1827, 1748, 5764],
       [4624, 4796, 4833, 2672, 9966]])

In [86]:
#Code here
arr2 = arr1[:,::2]
(arr2 - arr2.min()) / (arr2.max() - arr2.min())

array([[0.16996459, 0.71474693, 0.07935847],
       [0.22807748, 0.25557176, 0.077588  ],
       [0.1252864 , 0.62966049, 0.8209748 ],
       [0.        , 0.63705478, 0.07196417],
       [0.90616538, 0.63851281, 0.46021662],
       [0.09477192, 0.2938971 , 0.21172672],
       [0.07310977, 0.15236409, 0.56238284],
       [0.44365757, 0.46542387, 1.        ]])

###`Q-19:` Write a function which will accept 2 arguments.
First: A 1D numpy array arr

Second: An integer n {Please make sure n<=len(arr)}

Output: The output should be the nth largest item out of the array
```
# Example1 : arr=(12,34,40,7,1,0) and n=3, the output should be 12
# Example2 : arr=(12,34,40,7,1,0) and n=1, the output should be 40
```

In [94]:
#Code here
def nthmax(arr,n):
    if n>len(arr):
        raise IndexError("Invalid Index")
    arr.sort()
    return arr[-n]
nthmax(np.array([12,34,40,7,1,0]) ,2)

34

###`Q-20:` Create the following pattern without hardcoding. Use only numpy functions and the below input array a.
```
# Input: a = np.array([1,2,3])
# Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
```

In [101]:
#code here
a = np.array([1,2,3])
pattern1 = np.repeat(a,3)
pattern2 = np.tile(a,3)
print(pattern1)
print(pattern2)
merge = np.hstack([pattern1,pattern2])
merge

[1 1 1 2 2 2 3 3 3]
[1 2 3 1 2 3 1 2 3]


array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])