### 1. np.sort

Return a sorted copy of an array.

https://numpy.org/doc/stable/reference/generated/numpy.sort.html

In [1]:
# code
import numpy as np
a = np.random.randint(1,100,15)
a

array([71, 63, 67, 80, 86, 84, 20, 55, 31, 45, 58,  9, 38, 19, 67],
      dtype=int32)

In [2]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[26, 78, 60, 12],
       [29, 50, 76, 43],
       [28, 56, 20, 99],
       [42, 69, 64, 12],
       [90, 84, 68,  5],
       [45, 94, 75, 28]], dtype=int32)

In [3]:
np.sort(a)

array([ 9, 19, 20, 31, 38, 45, 55, 58, 63, 67, 67, 71, 80, 84, 86],
      dtype=int32)

In [4]:
np.sort(a)[::-1]

array([86, 84, 80, 71, 67, 67, 63, 58, 55, 45, 38, 31, 20, 19,  9],
      dtype=int32)

In [5]:
np.sort(b)

array([[12, 26, 60, 78],
       [29, 43, 50, 76],
       [20, 28, 56, 99],
       [12, 42, 64, 69],
       [ 5, 68, 84, 90],
       [28, 45, 75, 94]], dtype=int32)

In [7]:
# coulmn wise sort
np.sort(b,axis=0)

array([[26, 50, 20,  5],
       [28, 56, 60, 12],
       [29, 69, 64, 12],
       [42, 78, 68, 28],
       [45, 84, 75, 43],
       [90, 94, 76, 99]], dtype=int32)

In [8]:
# row wise sort
np.sort(b,axis=1)

array([[12, 26, 60, 78],
       [29, 43, 50, 76],
       [20, 28, 56, 99],
       [12, 42, 64, 69],
       [ 5, 68, 84, 90],
       [28, 45, 75, 94]], dtype=int32)

### 2. np.append

The numpy.append() appends values along the mentioned axis at the end of the array

https://numpy.org/doc/stable/reference/generated/numpy.append.html

In [9]:
np.append(a,200)

array([ 71,  63,  67,  80,  86,  84,  20,  55,  31,  45,  58,   9,  38,
        19,  67, 200])

In [10]:
np.append(a,[200,300,500])

array([ 71,  63,  67,  80,  86,  84,  20,  55,  31,  45,  58,   9,  38,
        19,  67, 200, 300, 500])

In [11]:
b

array([[26, 78, 60, 12],
       [29, 50, 76, 43],
       [28, 56, 20, 99],
       [42, 69, 64, 12],
       [90, 84, 68,  5],
       [45, 94, 75, 28]], dtype=int32)

In [27]:
# append random numbers column at the end of an array
np.append(b,np.round((np.random.random((b.shape[0],1))*100)),axis=1)

array([[26., 78., 60., 12., 97.],
       [29., 50., 76., 43., 81.],
       [28., 56., 20., 99., 65.],
       [42., 69., 64., 12., 46.],
       [90., 84., 68.,  5., 58.],
       [45., 94., 75., 28., 28.]])

In [26]:
# append random numbers row at the end of an array
np.append(b,np.round((np.random.random((1,b.shape[1]))*100)),axis=0)

array([[26., 78., 60., 12.],
       [29., 50., 76., 43.],
       [28., 56., 20., 99.],
       [42., 69., 64., 12.],
       [90., 84., 68.,  5.],
       [45., 94., 75., 28.],
       [14., 90., 33., 22.]])

In [29]:
# append ones numbers row at the end of an array
np.append(b,np.ones((1,b.shape[1])),axis=0)

array([[26., 78., 60., 12.],
       [29., 50., 76., 43.],
       [28., 56., 20., 99.],
       [42., 69., 64., 12.],
       [90., 84., 68.,  5.],
       [45., 94., 75., 28.],
       [ 1.,  1.,  1.,  1.]])

In [30]:
# append ones numbers column at the end of an array
np.append(b,np.ones((b.shape[0],1)),axis=1)

array([[26., 78., 60., 12.,  1.],
       [29., 50., 76., 43.,  1.],
       [28., 56., 20., 99.,  1.],
       [42., 69., 64., 12.,  1.],
       [90., 84., 68.,  5.,  1.],
       [45., 94., 75., 28.,  1.]])

### 3. np.concatenate

numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

In [31]:
# code
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [32]:
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [33]:
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

### 4. np.unique

With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.

https://numpy.org/doc/stable/reference/generated/numpy.unique.html/

In [34]:
# code
e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])

In [35]:
np.unique(e)

array([1, 2, 3, 4, 5, 6])

In [38]:
b

array([[26, 78, 60, 12],
       [29, 50, 76, 43],
       [28, 56, 20, 99],
       [42, 69, 64, 12],
       [90, 84, 68,  5],
       [45, 94, 75, 28]], dtype=int32)

In [41]:
np.unique(b,return_counts=True)

(array([ 5, 12, 20, 26, 28, 29, 42, 43, 45, 50, 56, 60, 64, 68, 69, 75, 76,
        78, 84, 90, 94, 99], dtype=int32),
 array([1, 2, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]))

In [43]:
np.unique(b,return_counts=True,return_index=True)

(array([ 5, 12, 20, 26, 28, 29, 42, 43, 45, 50, 56, 60, 64, 68, 69, 75, 76,
        78, 84, 90, 94, 99], dtype=int32),
 array([19,  3, 10,  0,  8,  4, 12,  7, 20,  5,  9,  2, 14, 18, 13, 22,  6,
         1, 17, 16, 21, 11]),
 array([1, 2, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]))

### 5. np.expand_dims

With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array

https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html

In [44]:
# code
a.shape

(15,)

In [46]:
np.expand_dims(a,axis=0)

array([[71, 63, 67, 80, 86, 84, 20, 55, 31, 45, 58,  9, 38, 19, 67]],
      dtype=int32)

In [47]:
np.expand_dims(a,axis=1)

array([[71],
       [63],
       [67],
       [80],
       [86],
       [84],
       [20],
       [55],
       [31],
       [45],
       [58],
       [ 9],
       [38],
       [19],
       [67]], dtype=int32)

In [52]:
np.expand_dims(b,axis=0)

array([[[26, 78, 60, 12],
        [29, 50, 76, 43],
        [28, 56, 20, 99],
        [42, 69, 64, 12],
        [90, 84, 68,  5],
        [45, 94, 75, 28]]], dtype=int32)

In [54]:
np.expand_dims(b,axis=0).shape

(1, 6, 4)

### 6. np.where

The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

https://numpy.org/doc/stable/reference/generated/numpy.where.html

In [48]:
a

array([71, 63, 67, 80, 86, 84, 20, 55, 31, 45, 58,  9, 38, 19, 67],
      dtype=int32)

In [50]:
# find all indices with value greater than 50 (return only true value index)
np.where(a>50)

(array([ 0,  1,  2,  3,  4,  5,  7, 10, 14]),)

In [55]:
# where(condition,True Value, False Value)
np.where(a>20,1,a)

array([ 1,  1,  1,  1,  1,  1, 20,  1,  1,  1,  1,  9,  1, 19,  1],
      dtype=int32)

In [56]:
# replace all values > 50 with 0
np.where(a>50,0,a)

array([ 0,  0,  0,  0,  0,  0, 20,  0, 31, 45,  0,  9, 38, 19,  0],
      dtype=int32)

In [57]:
np.where(a%2 == 0,0,a)

array([71, 63, 67,  0,  0,  0,  0, 55, 31, 45,  0,  9,  0, 19, 67],
      dtype=int32)

In [58]:
np.where(b%5==0,5,b)

array([[26, 78,  5, 12],
       [29,  5, 76, 43],
       [28, 56,  5, 99],
       [42, 69, 64, 12],
       [ 5, 84, 68,  5],
       [ 5, 94,  5, 28]], dtype=int32)

In [60]:
np.where(b%7==0,0,1)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [0, 0, 1, 1],
       [0, 1, 1, 1],
       [1, 0, 1, 1],
       [1, 1, 1, 0]])

In [64]:
np.where(b%7==0,"Good","Bad")

array([['Bad', 'Bad', 'Bad', 'Bad'],
       ['Bad', 'Bad', 'Bad', 'Bad'],
       ['Good', 'Good', 'Bad', 'Bad'],
       ['Good', 'Bad', 'Bad', 'Bad'],
       ['Bad', 'Good', 'Bad', 'Bad'],
       ['Bad', 'Bad', 'Bad', 'Good']], dtype='<U4')

In [63]:
# where does not support axis arguments
np.where(b%7==0,0,1,axis=1)

TypeError: where() got an unexpected keyword argument 'axis'

### 7. np.argmax

The numpy.argmax() function returns indices of the max element of the array in a particular axis.

https://numpy.org/doc/stable/reference/generated/numpy.argmax.html

In [66]:
# code
a

array([71, 63, 67, 80, 86, 84, 20, 55, 31, 45, 58,  9, 38, 19, 67],
      dtype=int32)

In [65]:
# 86 is the highest item in this array
np.argmax(a)

np.int64(4)

In [69]:
# 86 is the highest item in this array
print(a[np.argmax(a)])

86


In [70]:
b

array([[26, 78, 60, 12],
       [29, 50, 76, 43],
       [28, 56, 20, 99],
       [42, 69, 64, 12],
       [90, 84, 68,  5],
       [45, 94, 75, 28]], dtype=int32)

In [71]:
np.argmax(b)

np.int64(11)

In [77]:
b[np.argmax(b,axis=0)]

array([[90, 84, 68,  5],
       [45, 94, 75, 28],
       [29, 50, 76, 43],
       [28, 56, 20, 99]], dtype=int32)

In [76]:
np.argmax(b,axis=0)

array([4, 5, 1, 2])

In [74]:
np.argmax(b,axis=1)

array([1, 2, 3, 1, 0, 1])

In [78]:
# np.argmin
np.argmin(a)

np.int64(11)

### 8. np.cumsum

numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html

In [79]:
a

array([71, 63, 67, 80, 86, 84, 20, 55, 31, 45, 58,  9, 38, 19, 67],
      dtype=int32)

In [80]:
np.cumsum(a)

array([ 71, 134, 201, 281, 367, 451, 471, 526, 557, 602, 660, 669, 707,
       726, 793])

In [81]:
b

array([[26, 78, 60, 12],
       [29, 50, 76, 43],
       [28, 56, 20, 99],
       [42, 69, 64, 12],
       [90, 84, 68,  5],
       [45, 94, 75, 28]], dtype=int32)

In [82]:
np.cumsum(b,axis=0)

array([[ 26,  78,  60,  12],
       [ 55, 128, 136,  55],
       [ 83, 184, 156, 154],
       [125, 253, 220, 166],
       [215, 337, 288, 171],
       [260, 431, 363, 199]])

In [83]:
np.cumsum(b,axis=1)

array([[ 26, 104, 164, 176],
       [ 29,  79, 155, 198],
       [ 28,  84, 104, 203],
       [ 42, 111, 175, 187],
       [ 90, 174, 242, 247],
       [ 45, 139, 214, 242]])

In [84]:
# np.cumprod
np.cumprod(a)

array([                  71,                 4473,               299691,
                   23975280,           2061874080,         173197422720,
              3463948454400,      190517164992000,     5906032114752000,
         265771445163840000, -3032000254206831616, -8841258214151932928,
       -3926418811001522176,  -814981114190714880,   736497570350757888])

In [86]:
a

array([71, 63, 67, 80, 86, 84, 20, 55, 31, 45, 58,  9, 38, 19, 67],
      dtype=int32)

### 9. np.percentile

numpy.percentile()function used to compute the nth percentile of the given data (array elements) along the specified axis.

https://numpy.org/doc/stable/reference/generated/numpy.percentile.html

In [87]:
a

array([71, 63, 67, 80, 86, 84, 20, 55, 31, 45, 58,  9, 38, 19, 67],
      dtype=int32)

In [88]:
np.percentile(a,50)

np.float64(58.0)

In [89]:
np.median(a)

np.float64(58.0)

In [90]:
np.percentile(a,30)

np.float64(39.4)

In [91]:
np.percentile(b,50)

np.float64(53.0)

In [93]:
b

array([[26, 78, 60, 12],
       [29, 50, 76, 43],
       [28, 56, 20, 99],
       [42, 69, 64, 12],
       [90, 84, 68,  5],
       [45, 94, 75, 28]], dtype=int32)

In [92]:
np.percentile(b,50,axis=0)

array([35.5, 73.5, 66. , 20. ])

### 10. np.histogram

Numpy has a built-in numpy.histogram() function which represents the frequency of data distribution in the graphical form.

https://numpy.org/doc/stable/reference/generated/numpy.histogram.html

In [94]:
# code
a

array([71, 63, 67, 80, 86, 84, 20, 55, 31, 45, 58,  9, 38, 19, 67],
      dtype=int32)

In [95]:
np.histogram(a,bins=[0,10,20,30,40,50])

(array([1, 1, 1, 2, 1]), array([ 0, 10, 20, 30, 40, 50]))

In [101]:
# By default, np.histogram() flattens your 2D array into a 1D list 
b

array([[26, 78, 60, 12],
       [29, 50, 76, 43],
       [28, 56, 20, 99],
       [42, 69, 64, 12],
       [90, 84, 68,  5],
       [45, 94, 75, 28]], dtype=int32)

In [99]:
np.histogram(b,[0,10,20,30,40,50,60,70,80,90,100])

(array([1, 2, 5, 0, 3, 2, 4, 3, 1, 3]),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

### 11. np.corrcoef

Return Pearson product-moment correlation coefficients.

https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html

In [102]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

### 12. np.isin

With the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.

https://numpy.org/doc/stable/reference/generated/numpy.isin.html

In [103]:
# code
a


array([71, 63, 67, 80, 86, 84, 20, 55, 31, 45, 58,  9, 38, 19, 67],
      dtype=int32)

In [104]:
items = [10,20,30,40,50,60,70,80,90,100]

np.isin(a,items)

array([False, False, False,  True, False, False,  True, False, False,
       False, False, False, False, False, False])

In [105]:
np.isin(a,[10,20,30])

array([False, False, False, False, False, False,  True, False, False,
       False, False, False, False, False, False])

In [110]:
# in this example 71 and 20 is present out of these 3 items
a[np.isin(a,[71,65,20])]

array([71, 20], dtype=int32)

In [113]:
b

array([[26, 78, 60, 12],
       [29, 50, 76, 43],
       [28, 56, 20, 99],
       [42, 69, 64, 12],
       [90, 84, 68,  5],
       [45, 94, 75, 28]], dtype=int32)

In [114]:
np.isin(b,[10,20,85,71,76,12])

array([[False, False, False,  True],
       [False, False,  True, False],
       [False, False,  True, False],
       [False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [115]:
b[np.isin(b,[10,20,85,71,76,12])]

array([12, 76, 20, 12], dtype=int32)

### 13. np.flip

The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.

https://numpy.org/doc/stable/reference/generated/numpy.flip.html

In [121]:
# code
a

array([71, 63, 67, 80, 86, 84, 20, 55, 31, 45, 58,  9, 38, 19, 67],
      dtype=int32)

In [122]:
np.flip(a)

array([67, 19, 38,  9, 58, 45, 31, 55, 20, 84, 86, 80, 67, 63, 71],
      dtype=int32)

In [123]:
b

array([[26, 78, 60, 12],
       [29, 50, 76, 43],
       [28, 56, 20, 99],
       [42, 69, 64, 12],
       [90, 84, 68,  5],
       [45, 94, 75, 28]], dtype=int32)

In [124]:
np.flip(b,axis=1)

array([[12, 60, 78, 26],
       [43, 76, 50, 29],
       [99, 20, 56, 28],
       [12, 64, 69, 42],
       [ 5, 68, 84, 90],
       [28, 75, 94, 45]], dtype=int32)

In [125]:
np.flip(b,axis=0)

array([[45, 94, 75, 28],
       [90, 84, 68,  5],
       [42, 69, 64, 12],
       [28, 56, 20, 99],
       [29, 50, 76, 43],
       [26, 78, 60, 12]], dtype=int32)

### 14. np.put

The numpy.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array.

https://numpy.org/doc/stable/reference/generated/numpy.put.html

In [141]:
# code
a

array([110, 530,  67,  80,  86, 100, 200,  55,  31,  45,  58,   9,  38,
        19,  67], dtype=int32)

In [139]:
c = np.put(a,[0,1],[110,530])

In [140]:
print(c)

None


In [148]:
np.put(b,[0,1,5,6],[81,58,68,89])

In [149]:
b

array([[81, 58, 60, 12],
       [29, 68, 89, 43],
       [28, 56, 20, 99],
       [42, 69, 64, 12],
       [90, 84, 68,  5],
       [45, 94, 75, 28]], dtype=int32)

In [143]:
np.put(a,[15,16],[90,100])

IndexError: index 15 is out of bounds for axis 0 with size 15

In [145]:
np.insert(a,[5,8],[90,100])

array([110, 530,  67,  80,  86,  90, 100, 200,  55, 100,  31,  45,  58,
         9,  38,  19,  67], dtype=int32)

In [150]:
np.insert(b,[0,1,5,6],[100,100,100,100])

array([100,  81, 100,  58,  60,  12,  29, 100,  68, 100,  89,  43,  28,
        56,  20,  99,  42,  69,  64,  12,  90,  84,  68,   5,  45,  94,
        75,  28], dtype=int32)

### 15. np.delete

The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis.

https://numpy.org/doc/stable/reference/generated/numpy.delete.html

In [146]:
# code
a

array([110, 530,  67,  80,  86, 100, 200,  55,  31,  45,  58,   9,  38,
        19,  67], dtype=int32)

In [147]:
np.delete(a,[0,2,4])

array([530,  80, 100, 200,  55,  31,  45,  58,   9,  38,  19,  67],
      dtype=int32)

### 16. Set functions

- np.union1d
- np.intersect1d
- np.setdiff1d
- np.setxor1d
- np.in1d

In [151]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [152]:
np.intersect1d(m,n)

array([3, 4, 5])

In [153]:
np.setdiff1d(n,m)

array([6, 7])

In [154]:
np.setxor1d(m,n)

array([1, 2, 6, 7])

In [155]:
m[np.in1d(m,1)]

C:\Users\HP\AppData\Local\Temp\ipykernel_14496\524887286.py:1: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  m[np.in1d(m,1)]


array([1])

### 17. np.clip

numpy.clip() function is used to Clip (limit) the values in an array.

https://numpy.org/doc/stable/reference/generated/numpy.clip.html

In [156]:
# code
a

array([110, 530,  67,  80,  86, 100, 200,  55,  31,  45,  58,   9,  38,
        19,  67], dtype=int32)

In [157]:
np.clip(a,a_min=20,a_max=68)

array([68, 68, 67, 68, 68, 68, 68, 55, 31, 45, 58, 20, 38, 20, 67],
      dtype=int32)